### ISSUE TITLE
Commands support

### ISSUE THREAD

**Issue by remigarcia** [A-tG/voicemeeter-remote-api-extended#2]
Hello,

I did not find any way to use the Voicemeeter "Special Commands" (page 8 of the doc : https://download.vb-audio.com/Download_CABLE/VoicemeeterRemoteAPI.pdf).

Did I miss it or is it not implemented ?

If not implemented, with some hints I'll be glad to make a PR.

Thanks

**Comment by A-tG** [comment]
With `SetParameter()`
For example:
```csharp
vmrApi.SetParameter("Command.Show", 1);
```

**Comment by remigarcia** [comment]
> With `SetParameter()` For example:
> 
> ```cs
> vmrApi.SetParameter("Command.Show", 1);
> ```

Oh thanks, didn't even try this, sorry.
